sudo: false

dist: trusty

language: python

env:
    matrix:
        include:
        - python: "2.7"
          env:
            - PINTS_COMPILER=clang
            - PINTS_BUILD_TYPE=Release
        - python: "2.7"
          env:
            - PINTS_COMPILER=clang
            - PINTS_BUILD_TYPE=Debug
        - python: "2.7"
          env:
            - PINTS_COMPILER=gcc
            - PINTS_BUILD_TYPE=Debug
        - python: "3.6"
          env:
            - PINTS_COMPILER=clang
            - PINTS_BUILD_TYPE=Release
        - python: "3.6"
          env:
            - PINTS_COMPILER=gcc
            - PINTS_BUILD_TYPE=Debug

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - gcc-5
    - g++-5
    - clang-3.8

# command to install dependencies
install:
  - wget http://bitbucket.org/eigen/eigen/get/3.3.1.tar.gz; tar -xvf 3.3.1.tar.gz;mv eigen-eigen-* problems/electrochemistry/eigen3
  - pip install pints/.
  - pip install -r pints/requirements.txt
  - pip install -r pints/requirements-dev.txt

before_script:
- if [ "$PINTS_COMPILER" = "gcc" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$PINTS_COMPILER" = "clang" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
- printenv
- clang++ --version 2>&1 | grep clang
- g++ --version 2>&1 | grep g++
- python --version

script:
  - ./run-tests-electrochemistry.sh

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
    - michael.clerx@cs.ox.ac.uk
